esphome:
  name: rika-stove

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

uart:
  - id: rika_gsm_uart_bus
    tx_pin: GPIO16
    rx_pin: GPIO17
    baud_rate: 38400
  - id: rika_temp_uart_bus
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 38400

rika_gsm:
  id: ria_gsm_component_1
  uart_id: rika_gsm_uart_bus
  pin: "1234"
  # phone_number: "+33685967412"

text_sensor:
  - platform: rika_gsm
    raw_status:
      name: "Stove raw status"

binary_sensor:
  - platform: rika_gsm
    gsm_status:
      name: "GSM status"

rika_temperature:
  id: rika_temperature_component_1
  uart_id: rika_temp_uart_bus
  

api:
  encryption:
    key: !secret api_encryption_key
  services:
      - service: turn_on
        then:
          - rika_gsm.send_command:
              command: "ON"
      - service: turn_off
        then:
          - rika_gsm.send_command:
              command: "OFF"
      - service: send_command
        variables:
          command: string
        then:
          - rika_gsm.send_command:
              command: !lambda 'return command;'